services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: matchnet-backend-dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
